trigger:
- main   # or master branch

pool:
  name: Default 
  demands:
    - Agent.Name -equals agent1
  vmImage: 'windows-latest'

steps:
# Step 1: Use .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'   # Adjust to your .NET version

# Step 2: Cache NuGet packages
- task: Cache@2
  inputs:
    key: 'nuget | $(Agent.OS) | $(Build.SourcesDirectory)/**/*.csproj'
    restoreKeys: |
      nuget | $(Agent.OS)
    path: $(Pipeline.Workspace)/.nuget/packages

# Step 3: Restore NuGet packages
- script: dotnet restore
  displayName: 'Restore NuGet packages'

# Step 4: Build the project
- script: dotnet build --configuration Release
  displayName: 'Build Console App'

# Step 5: Run unit tests
- script: dotnet test --configuration Release
  displayName: 'Run Unit Tests for FindDuplicateString'
