trigger:
- main   # or master branch

#Below line will run only for a single program
# trigger:
#   branches:
#     include:
#       - main  # or master branch
#   paths:
#     include:
#       - path/to/your/program/**  # Add the specific directory or file path you want to track changes for

pool:
  name: Default 
  demands:
    - Agent.Name -equals agent1
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'   # Adjust to your .NET version

- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build --configuration Release
  displayName: 'Build Console App'

- script: dotnet test --configuration Release
  displayName: 'Run Unit Tests for FindDuplicateString'